# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tabnav}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Unboxed"]
  s.date = %q{2011-07-15}
  s.description = %q{Rails helper for generating navbars in a declarative manner}
  s.email = %q{github@unboxedconsulting.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/tabnav.rb",
    "lib/tabnav/helper.rb",
    "lib/tabnav/navbar.rb",
    "lib/tabnav/tab.rb",
    "spec/spec_helper.rb",
    "spec/tabnav/helper_spec.rb",
    "spec/tabnav/integration_spec.rb",
    "spec/tabnav/navbar_spec.rb",
    "spec/tabnav/tab_spec.rb"
  ]
  s.homepage = %q{http://github.com/unboxed/tabnav}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Rails helper for generating navbars}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.6.1"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.8"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.6.1"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.8"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.6.1"])
  end
end

