# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tabnav}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Unboxed"]
  s.date = %q{2010-07-30}
  s.description = %q{Rails helper for generating navbars in a declarative manner}
  s.email = %q{github@unboxedconsulting.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/tabnav.rb",
     "lib/tabnav/helper.rb",
     "lib/tabnav/navbar.rb",
     "lib/tabnav/tab.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tabnav/helper_spec.rb",
     "spec/tabnav/integration_spec.rb",
     "spec/tabnav/navbar_spec.rb",
     "spec/tabnav/tab_spec.rb"
  ]
  s.homepage = %q{http://github.com/unboxed/tabnav}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails helper for generating navbars}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/tabnav/helper_spec.rb",
     "spec/tabnav/integration_spec.rb",
     "spec/tabnav/navbar_spec.rb",
     "spec/tabnav/tab_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.2"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rspec-rails>, [">= 1.2.9"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.2"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rspec-rails>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.2"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rspec-rails>, [">= 1.2.9"])
  end
end

